//
//  StringConstants.swift
//  Mutelcor
//
//  Created by  on 21/03/17.
//  Copyright © 2017. All rights reserved.
//

import Foundation

//MARK:- Text Used On Screens
//===========================
//MARK: Screen Titles
//====================
let K_FORGOTPASSWORD_SCREEN_TITLE = "K_FORGOTPASSWORD_SCREEN_TITLE"
let K_APP_LABEL_ATBOTTOM = "K_APP_LABEL_ATBOTTOM"

//MARK: For LoginScreen
//======================
let K_SCREEN_TAG = "K_SCREEN_TAG"
let K_EMAIL_OR_MOBILE_NUMBER = "K_EMAIL_OR_MOBILE_NUMBER"
let K_PASSWORD = "K_PASSWORD"
let K_LOGIN_WITH_OTP = "K_LOGIN_WITH_OTP"
let K_FORGOT_PASSWORD = "K_FORGOT_PASSWORD"
let K_SECURE_LOGIN = "K_SECURE_LOGIN"
let K_NEW_USER_SIGN_UP = "K_NEW_USER_SIGN_UP"
let K_TERMS_AND_CONDITION = "K_TERMS_AND_CONDITION"

//MARK: For SignInWithOTPVC
//==========================
let K_SIGN_WITH_OTP = "K_SIGN_IN_WITH_OTP"
let K_OTP_VERIFICATION = "K_OTP_VERIFICATION"
let K_ENTER_OTP_ON_YOUR_MOBILE_NUMBER = "K_ENTER_OTP_ON_YOUR_MOBILE_NUMBER"

let K_BY_LOGGIN_IN = "K_BY_LOGGIN_IN"
let K_TERMS_AND_CONDITIONS = "K_TERMS_AND_CONDITIONS"
let K_THAT_YOU_HAVE = "K_THAT_YOU_HAVE"

//MARK: For Forgot PasswordVC
//==============================
let K_EMAIL_CONFIRMATION_MESSAGE = "K_EMAIL_CONFIRMATION_MESSAGE"
let K_FORGOTPASSWORD_SCREEN_LABEL = "K_FORGOTPASSWORD_SCREEN_LABEL"

//MARK: For Reset PasswordVC
//===========================
let K_RESET_PASSWORD = "K_RESET_PASSWORD"
let K_CONFIRM_PASSWORD = "K_CONFIRM_PASSWORD"
let CONFIRM_PASSWORD = "CONFIRM_PASSWORD"

//MARK: SignUPVC
//================
let K_SIGNUP_SCREEN_TITLE = "K_SIGNUP_SCREEN_TITLE"
let HELP_POP_UP_TITLE = "HELP_POP_UP_TITLE"
let HELP_POP_UP_MESSAGE = "HELP_POP_UP_MESSAGE"
let K_MOBILE_NUMBER = "K_MOBILE_NUMBER_PLACEHOLDER"
let K_AUTH_TEXT = "K_AUTH_TEXT"
let K_ENTER_AUTHORIZATION_CODE = "K_ENTER_AUTHORIZATION_CODE"

//MARK: COUNTRYCODEVC
//===================
let K_COUNTRYCODE_SCREEN_TITLE = "K_COUNTRYCODE_SCREEN_TITLE"

//MARK: For BuildProfileVC
//=========================
let BUILD_PROFILE_SCREEN_TITLE = "BUILD_PROFILE_SCREEN_TITLE"
let K_UPDATE_PROFILE_TITLE = "K_UPDATE_PROFILE_TITLE"
let K_SAVE_AND_CONTINUE_PLACEHOLDER = "K_SAVE_AND_CONTINUE_PLACEHOLDER"
let K_SKIP_PLACEHOLDER = "K_SKIP_PLACEHOLDER"
let K_BUILD_PROFILE = "K_BUILD_PROFILE"
let K_MEDICAL_PROFILE = "K_MEDICAL_PROFILE"
let K_ADDRESS_DETAIL = "K_ADDRESS_DETAIL"
let K_PERSONAL_INFORMATION = "K_PERSONAL_INFORMATION"

//MARK: For PersonalInformation VC
//==================================
let K_ALLERGIES = "K_ALLERGIES"
let K_HOSPITAL_DETAILS = "K_HOSPITAL_DETAILS"
let K_TREATMENT_DETAILS = "K_TREATMENT_DETAILS"
let K_PATIENT_NAME_PLACEHOLDER = "K_PATIENT_NAME_PLACEHOLDER"
let K_EMAIL_ADDRESS_PLACEHOLDER = "K_EMAIL_ADDRESS_PLACEHOLDER"
let K_DATE_OF_BIRTH_PLACEHOLDER = "K_DATE_OF_BIRTH_PLACEHOLDER"
let K_GENDER_PLACEHOLDER = "K_GENDER_PLACEHOLDER"
let K_FATHERS_NAME_PLACEHOLDER = "K_FATHERS_NAME_PLACEHOLDER"
let K_MOTHER_NAME_PLACEHOLDER = "K_MOTHER_NAME_PLACEHOLDER"
let K_GENDER_MALE_PLACEHOLDER = "K_GENDER_MALE_PLACEHOLDER"
let K_GENDER_FEMALE_PLACEHOLDER = "K_GENDER_FEMALE_PLACEHOLDER"
let K_GENDER_OTHERS_PLACEHOLDER = "K_GENDER_OTHERS_PLACEHOLDER"
let K_MOBILE_NUMBER_PLACEHOLDER = "K_MOBILE_NUMBER_PLACEHOLDER"
let K_SPOUSE_NAME_PLACEHOLDER = "K_SPOUSE_NAME_PLACEHOLDER"
let K_REFFERED_PLACEHOLDER = "K_REFFERED_PLACEHOLDER"
let K_EMERGENCY_CONSTACT_PLACEHOLDER = "K_EMERGENCY_CONSTACT_PLACEHOLDER"

let K_IDEAL_WEIGHT_PLACEHOLDER = "K_IDEAL_WEIGHT_PLACEHOLDER"
let K_MAXIMUM_LOSS_PLACEHOLDER = "K_MAXIMUM_LOSS_PLACEHOLDER"
let K_EXCESS_WEIGHT_PLACEHOLDER = "K_EXCESS_WEIGHT_PLACEHOLDER"
let K_WEIGHT_MAXIMUM_ACHIEVED = "K_WEIGHT_MAXIMUM_ACHIEVED"
let K_WEIGHT_MAXIMUM_LOSS = "K_WEIGHT_MAXIMUM_LOSS"
let K_FAMILY_HISTORY_OBESITY_REASON = "K_FAMILY_HISTORY_OBESITY_REASON"
let K_FAMILY_HISTORY_MEDICAL_DISEASES_REASON = "K_FAMILY_HISTORY_MEDICAL_DISEASES_REASON"
let K_EXCESS_APETITE_REASON = "K_EXCESS_APETITE_REASON"
let K_ALCOHOL_REASON = "K_ALCOHOL_REASON"
let K_TOBACOO_REASON = "K_TOBACOO_REASON"
let K_ILLEGAL_DRUG_REASON = "K_ILLEGAL_DRUG_REASON"
let K_TREATMENT_FOR_OBESITY = "K_TREATMENT_FOR_OBESITY"
let K_WAIST_CIRCUMFRENCE_PLACEHOLDER = "K_WAIST_CIRCUMFRENCE_PLACEHOLDER"
let K_HIP_CIRCUMFRENCE_PLACEHOLDER = "K_HIP_CIRCUMFRENCE_PLACEHOLDER"
let K_PAST_MEDICAL_COMPLIANTS_PLACEHOLDER = "K_PAST_MEDICAL_COMPLIANTS_PLACEHOLDER"
let K_NEUROLOGICAL_PLACEHOLDER = "K_NEUROLOGICAL_PLACEHOLDER"
let K_RESPIRATORY_PLACEHOLDER = "K_RESPIRATORY_PLACEHOLDER"
let K_CARDIAC_PLACEHOLDER = "K_CARDIAC_PLACEHOLDER"
let K_ABDOMINAL_PLACEHOLDER = "K_ABDOMINAL_PLACEHOLDER"
let K_JOINTS_AND_BONES_PLACEHOLDER = "K_JOINTS_AND_BONES_PLACEHOLDER"
let K_HORMONAL_PLACEHOLDER = "K_HORMONAL_PLACEHOLDER"
let K_PHYCHOLOGICAL_PLACEHOLDER = "K_PHYCHOLOGICAL_PLACEHOLDER"
let K_OTHERS_PLACEHOLDER = "K_OTHERS_PLACEHOLDER"
let K_PRESENT_MEDICAL_TREATMENT_PLACEHOLDER = "K_PRESENT_MEDICAL_TREATMENT_PLACEHOLDER"
let K_ENTER_EMAIL_ADDRESS_PLACEHOLDER = "K_ENTER_EMAIL_ADDRESS_PLACEHOLDER"
let K_ENTER_PIN_CODE_PLACEHOLDER = "K_ENTER_PIN_CODE_PLACEHOLDER"

let K_FAMILY_HISTORY_OBESITY = "K_FAMILY_HISTORY_OBESITY"
let K_FAMILY_HISTORY_MEDICAL_DISEASES = "K_FAMILY_HISTORY_MEDICAL_DISEASES"
let K_DO_YOU_LOVE_TO_EAT = "K_DO_YOU_LOVE_TO_EAT"
let K_DO_YOU_HAVE_AN_EXCESSIVE_APPETITE = "K_DO_YOU_HAVE_AN_EXCESSIVE_APPETITE"
let K_DO_YOU_HAVE_AN_ERRATIC_TIMMING = "K_DO_YOU_HAVE_AN_ERRATIC_TIMMING"
let K_EATING_VOLUMES = "K_EATING_VOLUMES"
let K_AFFINITY_FOR_SWEETS = "K_AFFINITY_FOR_SWEETS"
let K_ALCOHOL = "K_ALCOHOL"
let K_TOBACCO = "K_TOBACCO"
let K_ILLEGA_DRUGS = "K_ILLEGA_DRUGS"
let K_JUNK_FOOD_PER_WEEK = "K_JUNK_FOOD_PER_WEEK"
let K_ARE_YOU_OBESE = "K_ARE_YOU_OBESE"
let K_TREATMENT_SO_FAR_FOR_OBESITY = "K_TREATMENT_SO_FAR_FOR_OBESITY"

let K_OTHERS_DOCTOR = "K_OTHERS_DOCTOR"
let K_PATIENT_OCCUPATION = "K_PATIENT_OCCUPATION"

let K_CURRENT_ADDRESS_TYPE = "K_CURRENT_ADDRESS_TYPE"
let K_PERMANENT_ADDRESS_TYPE = "K_PERMANENT_ADDRESS_TYPE"

let K_MARITAL_STATUS = "K_MARITAL_STATUS"
let K_SERVICE_TEXT = "K_SERVICE_TEXT"
let K_BUSINESS_TEXT = "K_BUSINESS_TEXT"
let K_SINGLE_TEXT = "K_SINGLE_TEXT"
let K_MARRIED_TEXT = "K_MARRIED_TEXT"
let K_SEPRATE_TEXT = "K_SEPRATE_TEXT"
let K_OTHERS_TEXT = "K_OTHERS_TEXT"

//MARK: For Gender in PersonalInfromationVC
//===========================================
let K_MR_PLACEHOLDER = "K_MR_PLACEHOLDER"
let K_MRS_PLACEHOLDER = "K_MRS_PLACEHOLDER"
let K_MS_PLACEHOLDER = "K_MS_PLACEHOLDER"
let K_DR_PLACEHOLDER = "K_DR_PLACEHOLDER"

//MARK: For MedicalProfileVC
//===========================
let K_FEET_UNIT_PLACEHOLDER = "K_FEET_UNIT_PLACEHOLDER"
let K_CM_UNIT_PLACEHOLDER = "K_CM_UNIT_PLACEHOLDER"
let K_INCH_UNIT_PLACEHOLDER = "K_INCH_UNIT_PLACEHOLDER"
let K_HEIGHT_PLACEHOLDER = "K_HEIGHT_PLACEHOLDER"
let K_WEIGHT_PLACEHOLDER = "K_WEIGHT_PLACEHOLDER"
let K_BLOOD_GROUP_PLACEHOLDER = "K_BLOOD_GROUP_PLACEHOLDER"
let K_HYPERTENSION_PLACEHOLDER = "K_HYPERTENSION_PLACEHOLDER"
let K_FATHER_PLACEHOLDER = "K_FATHER_PLACEHOLDER"
let K_MOTHER_PLACEHOLDER = "K_MOTHER_PLACEHOLDER"
let K_DIABITIES_PLACEHOLDER = "K_DIABETES_PLACEHOLDER"
let K_SMOKING_PLACEHOLDER = "K_SMOKING_PLACEHOLDER"

let K_ADD_ALERGY_DETAILS_PLACEHOLDER = "K_ADD_ALERGY_DETAILS_PLACEHOLDER"
let K_CURRENT_MEDICATION_DETAILS_PLACEHOLDER = "K_CURRENT_MEDICATION_DETAILS_PLACEHOLDER"
let K_PREVIOUS_MEDICAL_HISTORY_PLACEHOLDER = "K_PREVIOUS_MEDICAL_HISTORY_PLACEHOLDER"

let K_FOOD_CATEGORY_DETAILS_PLACEHOLDER = "K_FOOD_CATEGORY_DETAILS_PLACEHOLDER"
let K_VEG_PLACEHOLDER = "K_VEG_PLACEHOLDER"
let K_NON_VEG_PLACEHOLDER = "K_NON_VEG_PLACEHOLDER"
let K_BOTH_PLACEHOLDER = "K_BOTH_PLACEHOLDER"

let K_ACTIVE_PLACEHOLDER = "K_ACTIVE_PLACEHOLDER"
let K_MODERATE_PLACEHOLDER = "K_MODERATE_PLACEHOLDER"
let K_SEDENTARY_PLACEHOLDER = "K_SEDENTARY_PLACEHOLDER"

let K_YES_PLACEHOLDER = "K_YES_PLACEHOLDER"
let K_NO_PLACEHOLDER = "K_NO_PLACEHOLDER"
let K_DONTKNOW_PLACEHOLDER = "K_DONTKNOW_PLACEHOLDER"

let K_LARGE_PLACEHOLDER = "K_LARGE_PLACEHOLDER"
let K_SMALL_PLACEHOLDER = "K_SMALL_PLACEHOLDER"

let K_ADD_HOSPITAL_DETAILS_PLACEHOLDER = "K_ADD_HOSPITAL_DETAILS_PLACEHOLDER"
let K_DOCTOR_NAME_PLACEHOLDER = "K_DOCTOR_NAME_PLACEHOLDER"
let K_DOCTOR_ADDRESS_PLACEHOLDER = "K_DOCTOR_ADDRESS_PLACEHOLDER"
let K_ASSOSIATED_DOCTOR = "K_ASSOSIATED_DOCTOR"

let K_SPECIALITY_PLACEHOLDER = "K_SPECIALITY_PLACEHOLDER"
let K_ADD_TREATMENT_DETAILS_PLACEHOLDER = "K_ADD_TREATMENT_DETAILS_PLACEHOLDER"
let K_TYPE_OF_SURGERY_PLACEHOLDER = "K_TYPE_OF_SURGERY_PLACEHOLDER"
let K_DATE_OF_ADMISSION_PLACEHOLDER = "K_DATE_OF_ADMISSION_PLACEHOLDER"
let K_DATE_OF_SURGERY_PLACEHOLDER = "K_DATE_OF_SURGERY_PLACEHOLDER"
let K_DATE_OF_DISCHARGE_PLACEHOLDER = "K_DATE_OF_DISCHARGE_PLACEHOLDER"
let K_REASON_OF_REVISION_PLACEHOLDER = "K_REASON_OF_REVISION_PLACEHOLDER"
let K_SURGERY_PROCEDURE_PLACEHOLDER = "K_SURGERY_PROCEDURE_PLACEHOLDER"
let K_OPERATIVE_APPROACH_PLACEHOLDER = "K_OPERATIVE_APPROACH_PLACEHOLDER"

let K_PRESENT_PLACEHOLDER = "K_PRESENT_PLACEHOLDER"
let K_PAST_PLACEHOLDER = "K_PAST_PLACEHOLDER"
let K_IF_YES_WHO_ALL = "K_IF_YES_WHO_ALL"
let K_IF_HOW_OFTEN_TO_EAT = "K_IF_HOW_OFTEN_TO_EAT"
let K_IF_QTY_AND_PERIOD = "K_IF_QTY_AND_PERIOD"
let K_IF_ADD_DESCRIPTION = "K_IF_ADD_DESCRIPTION"
let K_ENTER_ALLERGIES_DETAIL = "K_ENTER_ALLERGIES_DETAIL"
let K_WRITE_HERE = "K_WRITE_HERE"
let K_SELECT_PLACEHOLDER = "K_SELECT_PLACEHOLDER"
let K_PHONE_NUMBER_PLACEHOLDER = "K_PHONE_NUMBER_PLACEHOLDER"
let K_COUNTRY_CODE_PLACEHOLDER = "K_COUNTRY_CODE_PLACEHOLDER"
let K_SELECT_COUNTRY_PLACEHOLDER = "K_SELECT_COUNTRY_PLACEHOLDER"
let K_SELECT_STATE_PLACEHOLDER = "K_SELECT_STATE_PLACEHOLDER"
let K_SELECT_CITY_PLACEHOLDER = "K_SELECT_CITY_PLACEHOLDER"
let K_SELECT_ETHINICITY_PLACEHOLDER = "K_SELECT_ETHINICITY_PLACEHOLDER"

let K_ENTER_YOUR_ADDRESS_PLACEHOLDER = "K_ENTER_YOUR_ADDRESS_PLACEHOLDER"
let K_ENTER_PERSON_NAME_PLACEHOLDER = "K_ENTER_PERSON_NAME_PLACEHOLDER"
let K_SELECT_OCCUPATION_PLACEHOLDER = "K_SELECT_OCCUPATION_PLACEHOLDER"
let K_SELECT_MARITAL_PLACEHOLDER = "K_SELECT_MARITAL_PLACEHOLDER"
let K_ENTER_YOUR_FATHER_NAME_PLACEHOLDER = "K_ENTER_YOUR_FATHER_NAME_PLACEHOLDER"
let K_ENTER_YOUR_MOTHER_NAME_PLACEHOLDER = "K_ENTER_YOUR_MOTHER_NAME_PLACEHOLDER"
let K_ENTER_YOUR_SPOUSE_NAME_PLACEHOLDER = "K_ENTER_YOUR_SPOUSE_NAME_PLACEHOLDER"
let K_ENTER_EMERGENCY_CONTACT_PERSON_PLACEHOLDER = "K_ENTER_EMERGENCY_CONTACT_PERSON_PLACEHOLDER"
let K_ENTER_YRELATION_PLACEHOLDER = "K_ENTER_YRELATION_PLACEHOLDER"


//MARK: Height Unit
//==================
let K_FEET_PLACEHOLDER = "K_FEET_PLACEHOLDER"
let K_CM_PLACEHOLDER = "K_CM_PLACEHOLDER"

//MARK: Weight Unit
//=================
let K_KG_PLACEHOLDER = "K_KG_PLACEHOLDER"
let K_LBS_PLACEHOLDER = "K_LBS_PLACEHOLDER"

//MARK:- Waist Unit
//=================
let K_INCH_PLACEHOLDER = "K_INCH_PLACEHOLDER"
//MARK: Blood Type
//=================
let A_PLUS_PLACEHOLDER = "A_PLUS_PLACEHOLDER"
let A_NEGATIVE_PLACEHOLDER = "A_NEGATIVE_PLACEHOLDER"
let B_PLUS_PLACEHOLDER = "B_PLUS_PLACEHOLDER"
let B_NEGATIVE_PLACEHOLDER = "B_NEGATIVE_PLACEHOLDER"
let O_PLUS_PLACEHOLDER = "O_PLUS_PLACEHOLDER"
let O_NEGATIVE_PLACEHOLDER = "O_NEGATIVE_PLACEHOLDER"
let AB_PLUS_PLACEHOLDER = "AB_PLUS_PLACEHOLDER"
let AB_NEGATIVE_PLACEHOLDER = "AB_NEGATIVE_PLACEHOLDER"

let K_ENVIRONMENTAL_PLACEHOLDER = "K_ENVIRONMENTAL_PLACEHOLDER"
let K_FOOD_PLACEHOLDER = "K_FOOD_PLACEHOLDER"
let K_DRUG_PLACEHOLDER = "K_DRUG_PLACEHOLDER"
let K_MILD_SEVERITIY = "K_MILD_SEVERITIY"
let K_MODERATE_SEVERITIY = "K_MODERATE_SEVERITIY"
let K_SEVERE_SEVERITIY = "K_SEVERE_SEVERITIY"

//MARK: For AddressDetailVC
//==========================
let K_COUNTRY_PLACEHOLDER = "K_COUNTRY_PLACEHOLDER"
let K_ETHNICITY_PLACEHOLDER = "K_ETHNICITY_PLACEHOLDER"
let K_PIN_CODE_PLACEHOLDER = "K_PIN_CODE_PLACEHOLDER"
let K_STATE_PLACEHOLDER = "K_STATE_PLACEHOLDER"
let K_TOWN_PLACEHOLDER = "K_TOWN_PLACEHOLDER"
let K_ADDRESS_TYPE = "K_ADDRESS_TYPE"
let K_ADDRESS_LINE1_PLACEHOLDER = "K_ADDRESS_LINE1_PLACEHOLDER"
let K_ADDRESS_LINE_2 = "K_ADDRESS_LINE_2"
let K_CREATE_PROFILE_PLACEHOLDER = "K_CREATE_PROFILE_PLACEHOLDER"
let K_EMERGENCY_CONTACT_PERSON = "K_EMERGENCY_CONTACT_PERSON"
let K_NAME_PLACEHOLDER = "K_NAME_PLACEHOLDER"
let K_RELATIONSHIP_PLACEHOLDER = "K_RELATIONSHIP_PLACEHOLDER"
let K_CONTACT_NUMBER_PLACEHOLDER = "K_CONTACT_NUMBER_PLACEHOLDER"


//MARK: BASEVIEWCONTROLLER
//==========================
let K_DASHBOARD_SCREEN_TITLE = "K_DASHBOARD_SCREEN_TITLE"
let K_APPOINTMENT_SCREEN_TITLE = "K_APPOINTMENT_SCREEN_TITLE"
let K_MEASUREMENT_SCREEN_TITLE = "K_MEASUREMENT_SCREEN_TITLE"
let K_NUTRITION_SCREEN_TITLE = "K_NUTRITION_SCREEN_TITLE"
let K_ACTIVITY_SCREEN_TITLE = "K_ACTIVITY_SCREEN_TITLE"
let K_CALENDER_SCREEN_TITLE = "K_CALENDER_SCREEN_TITLE"
let K_EPRESCRIPTION_SCREEN_TITLE = "K_EPRESCRIPTION_SCREEN_TITLE"
let K_MEDICATION_REMINDER_SCREEN_TITLE = "K_MEDICATION_REMINDER_SCREEN_TITLE"
let K_ATTACH_REPORT = "K_ATTACH_REPORT"
let K_ADD_IMAGE = "K_ADD_IMAGE"
let K_UPLOAD_IMAGE_TITLE = "K_UPLOAD_IMAGE_TITLE"

//MARK: DASHBOARDVC
//==================
let K_MY_BMI = "K_MY_BMI"
let K_NEXT_SCHEDULE = "K_NEXT_SCHEDULE"
let K_LAST_SEEN = "K_LAST_SEEN"
let K_LAST_APPOINTMENT_DATE = "K_LAST_APPOINTMENT_DATE"
let K_LAST_REVIEWED = "K_LAST_REVIEWED"
let K_CALORIES_CONSUMED_TEXT = "K_CALORIES_CONSUMED_TEXT"
let K_CALORIES_BURNT_TEXT = "K_CALORIES_BURNT_TEXT"
let K_WATER_INTAKE_TEXT = "K_WATER_INTAKE_TEXT"
let K_BEFORE = "K_BEFORE"
let K_AFTER = "K_AFTER"
let K_TIMELINE_PROGRESE = "K_TIMELINE_PROGRESE"



//MARK: DateVC
//==============
let K_CANCEL_BUTTON = "K_CANCEL_BUTTON"
let K_DONE_BUTTON = "K_DONE_BUTTON"

//MARK: ConfirmationVC
//==============
let K_CONFIRM_BUTTON = "K_CONFIRM_BUTTON"
let K_CONFIRMATION_BUTTON = "K_CONFIRMATION_BUTTON"
let K_CONFIRMATION_CANCEL_BUTTTON = "K_CONFIRMATION_CANCEL_BUTTTON"
let K_BOOK_APPOINTMENT_CONFIRMATION = "K_BOOK_APPOINTMENT_CONFIRMATION"

//MARK: ActivityVC
//===========
let K_DURATION_BUTTON = "K_DURATION_BUTTON"
let K_DISTANCE_BUTTON = "K_DISTANCE_BUTTON"
let K_CALORIES_BUTTON = "K_CALORIES_BUTTON"
let K_LAST7DAYS = "K_LAST7DAYS"
let K_AVG = "K_AVG"
let K_MINUTES_UNIT = "K_MINUTES_UNIT"
let K_MINUTE_UNIT = "K_MINUTE_UNIT"
let K_KILOMETER_UNIT = "K_KILOMETER_UNIT"
let K_KILOMETERS_UNIT = "K_KILOMETERS_UNIT"
let K_CALORIES_UNIT = "K_CALORIES_UNIT"

//MARK: AddActivityVC
//==============
let K_ADD_ACTIVITY_SCREEN_TITLE = "K_ADD_ACTIVITY_SCREEN_TITLE"
let K_DATE_TEXT = "K_DATE_TEXT"
let K_TIME_TEXT = "K_TIME_TEXT"
let K_SUBMIT_BUTTON = "K_SUBMIT_BUTTON"
let K_MY_RECENT = "K_MY_RECENT"
let K_DISTANCE_UNIT_KMS = "K_DISTANCE_UNIT_KMS"
let K_DISTANCE_UNIT_MILES = "K_DISTANCE_UNIT_MILES"
let K_DURATION_UNIT_MINS = "K_DURATION_UNIT_MINS"
let K_DURATION_UNIT_HOURS = "K_DURATION_UNIT_HOURS"

//MARK: ActivityplanVC
//====================
let K_ACTIVITY_PLAN_SCREEN_TITLE = "K_ACTIVITY_PLAN_SCREEN_TITLE"
let K_CURRENT_TITLE = "K_CURRENT_TITLE"
let K_PREVIOUS_TITLE = "K_PREVIOUS_TITLE"
let K_NO_ACTIVITY_PLAN = "K_NO_ACTIVITY_PLAN"
let K_NO_RECENT_ACTIVITY = "K_NO_RECENT_ACTIVITY"

//MARK: DosDontsVC
//================
let K_DOS_TITLE = "K_DOS_TITLE"
let K_DONTS_TITLE = "K_DONTS_TITLE"
let K_FOODS_TO_AVOID_TITLE = "K_FOODS_TO_AVOID_TITLE"
let K_DAILY_ALLOWANCES_TITLE = "K_DAILY_ALLOWANCES_TITLE"
let K_ATTACHMENTS_TITLE = "K_ATTACHMENTS_TITLE"
let K_POINTS_TO_REMEMBER = "K_POINTS_TO_REMEMBER"

//MARK: MedicationReminderVC
//==========================
let K_SET_REMINDER = "K_SET_REMINDER_TITLE"
let K_EXISTING_REMINDER = "K_EXISTING_REMINDER_TITLE"
let K_NAME_OF_DRUG = "K_NAME_OF_DRUG"
let K_START_DATE_TITLE = "K_START_DATE_TITLE"
let K_END_DATE_TITLE = "K_END_DATE_TITLE"
let K_WEEKLY_BUTTON_TITLE = "K_WEEKLY_BUTTON_TITLE"
let K_MONTHLY_BUTTON_TITLE = "K_MONTHLY_BUTTON_TITLE"
let K_RECURRENCE_TITLE = "K_RECURRENCE_TITLE"
let K_SCHEDULE_TITLE = "K_SCHEDULE_TITLE"
let K_REMINDER_TIME_TITLE = "K_REMINDER_TIME_TITLE"
let K_DOSAGE_TITLE = "K_DOSAGE_TITLE"
let K_INSTRUCTTIONS_TITLE = "K_INSTRUCTTIONS_TITLE"
let K_ONCE_A_DAY_TITLE = "K_ONCE_A_DAY_TITLE"
let K_TWICE_A_DAY_TITLE = "K_TWICE_A_DAY_TITLE"
let K_THRICE_A_DAY_TITLE = "K_THRICE_A_DAY_TITLE"
let K_ONE_PILLS_TITLE = "K_ONE_PILLS_TITLE"
let K_TWO_PILLS_TITLE = "K_TWO_PILLS_TITLE"
let K_THREE_PILLS_TITLE = "K_THREE_PILLS_TITLE"
let K_PILL = "K_PILL"
let K_PILLS = "K_PILLS"
let K_BEFORE_MEAL_TITLE = "K_BEFORE_MEAL_TITLE"
let K_AFTER_MEAL_TITLE = "K_AFTER_MEAL_TITLE"
let K_DURING_MEAL_TITLE = "K_DURING_MEAL_TITLE"
let K_NONE_TITLE = "K_NONE_TITLE"
let K_SUN_TITLE = "K_SUN_TITLE"
let K_MON_TITLE = "K_MON_TITLE"
let K_TUE_TITLE = "K_TUE_TITLE"
let K_WED_TITLE = "K_WED_TITLE"
let K_THUR_TITLE = "K_THUR_TITLE"
let K_FRI_TITLE = "K_FRI_TITLE"
let K_SAT_TITLE = "K_SAT_TITLE"
let K_DELETE_REMINDER_CONFIRMATION = "K_DELETE_REMINDER_CONFIRMATION"

//MARK: SearchFoodVC
//==================
let K_SELECT_FOOD_SCREEN_TITLE = "K_SELECT_FOOD_SCREEN_TITLE"

//MARK: WeekPerformanceVC
//=======================
let K_NUTRITION_PLAN_TITLE = "K_NUTRITION_PLAN_TITLE"
let K_MY_NUTRITION_TITLE = "K_MY_NUTRITION_TITLE"
let K_DAYS_TITLE = "K_DAYS_TITLE"
let K_WEEK_PERFORMANCE_SCREEN_TITLE = "K_WEEK_PERFORMANCE_SCREEN_TITLE"

//MARK: NutritionVC
//==================
let K_CALORIES_TITLE = "K_CALORIES_TITLE"
let K_CARBS_CAPS_TITLE = "K_CARBS_CAPS_TITLE"
let K_FATS_CAPS_TITLE = "K_FATS_CAPS_TITLE"
let K_PROTIEN_CAPS_TITLE = "K_PROTIEN_CAPS_TITLE"
let K_WATER_CAPS_TITLE = "K_WATER_CAPS_TITLE"
let K_ALL_TITLE = "K_ALL_TITLE"
let K_BREAKFAST_TITLE = "K_BREAKFAST_TITLE"
let K_LUNCH_TITLE = "K_LUNCH_TITLE"
let K_DINNER_TITLE = "K_DINNER_TITLE"
let K_SNACKS_TITLE = "K_SNACKS_TITLE"
let K_ALL_SMALL_TITLE = "K_ALL_SMALL_TITLE"
let K_BREAKFAST_SMALL_TITLE = "K_ALL_SMALL_TITLE"
let K_LUNCH_SMALL_TITLE = "K_ALL_SMALL_TITLE"
let K_DINNER_SMALL_TITLE = "K_ALL_SMALL_TITLE"
let K_SNACKS_SMALL_TITLE = "K_ALL_SMALL_TITLE"
let K_WEEK_PERFORMANCE_TITLE = "K_WEEK_PERFORMANCE_TITLE"
let K_GRAM_TITLE = "K_GRAM_TITLE"
let K_KILOGRAM_TITLE = "K_KILOGRAM_TITLE"
let K_LITRE_TITLE = "K_LITRE_TITLE"
let K_PREVIOUS_ATTACHMENT = "K_PREVIOUS_ATTACHMENT"
let K_NO_PREVIOUS_DATES = "K_NO_PREVIOUS_DATES"
let K_TODAY_TITLE = "K_TODAY_TITLE"

//MARK: NutritionPlanVC
//======================
let K_NUTRITION_PLAN_SCREEN_TITLE = "K_NUTRITION_PLAN_SCREEN_TITLE"
let K_CARB_TITLE = "K_CARB_TITLE"
let K_FATS_TITLE = "K_FATS_TITLE"
let K_PROTIENS_TITLE = "K_PROTIENS_TITLE"
let K_WATER_TITLE = "K_WATER_TITLE"
let K_NUTRIENTS_TITLE = "K_NUTRIENTS_TITLE"
let K_TARGET_TITLE = "K_TARGET_TITLE"
let K_CONSUMED_TITLE = "K_CONSUMED_TITLE"
let K_NO_NUTRITION_PLAN = "K_NO_NUTRITION_PLAN"


//MARK: AddNutritionVC
//====================
let K_ADD_WATER = "K_ADD_WATER"
let K_ADD_FOOD = "K_ADD_FOOD"
let K_SELECTMEAL_WATER = "K_SELECTMEAL_WATER"
let K_ADD_NUTRITION_SCREEN_TITLE = "K_ADD_NUTRITION_SCREEN_TITLE"
let K_ADD_FOOD_TITLE = "K_ADD_FOOD_TITLE"

//MARK: MessagesVC
//=================
let K_YEARS_AGO = "K_YEARS_AGO"
let K_YEAR_AGO = "K_YEAR_AGO"
let K_MONTHS_AGO = "K_MONTHS_AGO"
let K_MONTH_AGO = "K_MONTH_AGO"
let K_DAYS_AGO = "K_DAYS_AGO"
let K_DAY_AGO = "K_DAY_AGO"
let K_HOURS_AGO = "K_HOURS_AGO"
let K_HOUR_AGO = "K_HOUR_AGO"
let K_MINUTES_AGO = "K_MINUTES_AGO"
let K_MINUTE_AGO = "K_MINUTE_AGO"
let K_JUST_NOW = "K_JUST_NOW"

//MARK: NotificationVC
//====================
let K_NOTIFICATION_SCREEN_TITLE = "K_NOTIFICATION_SCREEN_TITLE"
let K_NO_NOTIFICATION = "K_NO_NOTIFICATION"
let K_NO_LOGBOOK = "K_NO_LOGBOOK"

//MARK: ADD AddAppointmentVC
//===========================
let K_NATURE_OF_APPOINTMENT = "K_NATURE_OF_APPOINTMENT"
let K_VISIT_TYPE = "K_VISIT_TYPE"
let K_SYMPTOMS = "K_SYMPTOMS"
let K_APPOINTMENT_DATE = "K_APPOINTMENT_DATE"
let K_VIDEO_CONSULTATION = "K_VIDEO_CONSULTATION"
let K_PHYSICAL_CONSULTATION = "K_PHYSICAL_CONSULTATION"
let K_ADD_APPOINTMENT_SCREEN_TITLE = "K_ADD_APPOINTMENT_SCREEN_TITLE"
let K_RESCHEDULE_APPOINTMENT_SCREEN_TITLE = "K_RESCHEDULE_APPOINTMENT_SCREEN_TITLE"
let K_APPOINTMENT_BOOKED = "K_APPOINTMENT_BOOKED"
let K_SUCCESSFULLY = "K_SUCCESSFULLY"

//MARK: SymptomVC
//===============
let K_OTHER_TITLE = "K_OTHER_TITLE"
let K_CHOOSE_SYMPTOMS_TITLE = "K_CHOOSE_SYMPTOMS_TITLE"
let K_TIME_SLOTS = "K_TIME_SLOTS"
let K_OK_THANKS_TITLE = "K_OK_THANKS_TITLE"
let K_PLEASE_SPECIFY = "K_PLEASE_SPECIFY"

//MARK: AppointmentListingVC
//==========================
let K_PENDING_STATUS = "K_PENDING_STATUS"
let K_APPROVED_STATUS = "K_APPROVED_STATUS"
let K_ATTENDED_STATUS = "K_ATTENDED_STATUS"
let K_RESCHEDULED_STATUS = "K_RESCHEDULED_STATUS"
let K_CANCELLED_STATUS = "K_CANCELLED_STATUS"
let K_UPCOMING_APPOINTMENT_TITLE = "K_UPCOMING_APPOINTMENT_TITLE"
let K_APPOINTMENT_HISTORY_TITLE = "K_APPOINTMENT_HISTORY_TITLE"
let K_APPOINTMENT_LISTING_SCREN_TITLE = "K_APPOINTMENT_LISTING_SCREN_TITLE"
let K_NO_UPCOMING_APPOINTMENTS = "K_NO_UPCOMING_APPOINTMENTS"
let K_NO_APPOINTMENT_HISTORY = "K_NO_APPOINTMENT_HISTORY"
let K_NO_APPOINTMENT_SCHEDULED = "K_NO_APPOINTMENT_SCHEDULED"
let K_CANCEL_APPOINTMENT_TITLE = "K_CANCEL_APPOINTMENT_TITLE"
let K_RESCHEDULE_STATUS = "K_RESCHEDULE_STATUS"

let K_ROUTINE_STATUS = "K_ROUTINE_STATUS"
let K_EMERGENCY_STATUS = "K_EMERGENCY_STATUS"
let K_SYMPTOMS_TITLE = "K_SYMPTOMS_TITLE"


//MARK: BuildProfileVC
//====================
let K_GALLERY_TITLE = "K_GALLERY_TITLE"
let K_CAMERA_TITLE = "K_CAMERA_TITLE"
let K_OK_TITLE = "K_OK_TITLE"

//MARK: MyMeasurementVC
//=====================
let K_ATTACHED_REPORTS = "K_ATTACHED_REPORTS"

//MARK: VITALVC
//=============
let K_NO_MEASUREMENT_DATA = "K_NO_MEASUREMENT_DATA"

//MARK: AddMeasurementVC
//======================
let K_ADD_MEASUREMENT_SCREEN_TITLE = "K_ADD_MEASUREMENT_SCREEN_TITLE"
let K_SELECT_TIME_TITLE = "K_SELECT_TIME_TITLE"
let K_ICLOUD_TITLE = "K_ICLOUD_TITLE"
let K_SAVE_BUTTON_TITLE = "K_SAVE_BUTTON_TITLE"
let K_ADD_ATTACHMENT_BUTTON_TITLE = "K_ADD_ATTACHMENT_BUTTON_TITLE"

//MARK: ImageDetailVC
//====================
let K_IMAGE_DETAIL_SCREEN_TITLE = "K_IMAGE_DETAIL_SCREEN_TITLE"

//MARK: MyMesurementDetailVC
//=========================
let K_MY_MEASUREMENTS_DETAIL_SCREEN_TITLE_PLACEHOLDER = "K_MY_MEASUREMENTS_DETAIL_SCREEN_TITLE_PLACEHOLDER"
let K_SELECT_TEST_NAME_PLACEHOLDER = "K_SELECT_TEST_NAME_PLACEHOLDER"
let K_ONE_WEEK_BUTTON_TITLE_PLACEHOLDER = "K_ONE_WEEK_BUTTON_TITLE_PLACEHOLDER"
let K_ONE_MONTH_BUTTON_TITLE_PLACEHOLDER = "K_ONE_MONTH_BUTTON_TITLE_PLACEHOLDER"
let K_THREE_MONTH_BUTTON_TITLE_PLACEHOLDER = "K_THREE_MONTH_BUTTON_TITLE_PLACEHOLDER"
let K_SIX_MONTH_BUTTON_TITLE_PLACEHOLDER = "K_SIX_MONTH_BUTTON_TITLE_PLACEHOLDER"
let K_ONE_YEAR_BUTTON_TITLE_PLACEHOLDER = "K_ONE_YEAR_BUTTON_TITLE_PLACEHOLDER"
let K_ALL_BUTTON_TITLE_PLACEHOLDER = "K_ALL_BUTTON_TITLE_PLACEHOLDER"
let K_ATTACHMENTS_SECTION_TITLE_PLACEHOLDER = "K_ATTACHMENTS_SECTION_TITLE_PLACEHOLDER"
let K_NO_ATTACHED_REPORTS = "K_NO_ATTACHED_REPORTS"

//MARK: SideMenuVC
//================
let K_GENERATE_HEALTH_REPORT_TITLE = "K_GENERATE_HEALTH_REPORT_TITLE"
let K_LOG_BOOK_TITLE = "K_LOG_BOOK_TITLE"
let K_DISCHARGE_SUMMARY_TITLE = "K_DISCHARGE_SUMMARY_TITLE"
let K_MESSAGE_TITLE = "K_MESSAGE_TITLE"
let K_NOTIFICATION_TITLE = "K_NOTIFICATION_TITLE"
let K_CONNECTED_DEVICES_TITLE = "K_CONNECTED_DEVICES_TITLE"
let K_USER_GUIDE_TITLE = "K_USER_GUIDE_TITLE"
let K_HELP_FAQ_TITLE = "K_HELP_FAQ_TITLE"

//MARK: DischargeSummaryVC
//=========================
let K_LAST_DISCHARGE_SUMMARY = "K_LAST_DISCHARGE_SUMMARY"
let K_FINAL_DIAGNOSIS = "K_FINAL_DIAGNOSIS"
let K_PROCEDURES = "K_PROCEDURES"
let K_HOSPITAL_COURSE = "K_HOSPITAL_COURSE"
let K_DISCHARGE_MEDICATION = "K_DISCHARGE_MEDICATION"
let K_FOLLOW_UP_APPOINTMENT = "K_FOLLOW_UP_APPOINTMENT"
let K_DISCHARGE_ADVICE = "K_DISCHARGE_ADVICE"
let K_LABORATORY_DATA = "K_LABORATORY_DATA"
let K_ILLNESS_HISTORY = "K_ILLNESS_HISTORY"

//MARK: SettingVC
//================
let K_CHANGE_PASSWORD_TITLE = "K_CHANGE_PASSWORD_TITLE"
let K_CHANGE_PHONENUMBER_TITLE = "K_CHANGE_PHONENUMBER_TITLE"
let K_TERMS_AND_CONDITION_TITLE = "K_TERMS_AND_CONDITION_TITLE"
let K_PRIVACY_POLICY = "K_PRIVACY_POLICY"
let K_ABOUT_APP = "K_ABOUT_APP"
let K_LOGOUT = "K_LOGOUT"
let K_SETTINGS_SCREEN_TITLE = "K_SETTINGS_SCREEN_TITLE"
let K_LOG_OUT_CONFIRMATION = "K_LOG_OUT_CONFIRMATION"

//MARK: ChangePasswordVC
//======================
let K_OLD_PASSWORD = "K_OLD_PASSWORD"
let K_NEW_PASSWORD = "K_NEW_PASSWORD"
let K_CONFIRM_NEW_PASSWORD = "K_CONFIRM_NEW_PASSWORD"
let K_CHANGE_PASSWORD_CONFIRMATION_TEXT = "K_CHANGE_PASSWORD_CONFIRMATION_TEXT"
let K_NEW_MOBILE_NUMBER = "K_NEW_MOBILE_NUMBER"
let K_OTP_SEND_OLD_NUMBER = "K_OTP_SEND_OLD_NUMBER"
let K_CONFIRMATION = "K_CONFIRMATION"

//MARK: GenrateHealthReportVC
//===========================
let K_GENERATE_HEALTH_REPORT_BUTTON_TITLE = "K_GENERATE_HEALTH_REPORT_BUTTON_TITLE"

//MARK: CMSVC
//=============
let K_CMS_SCREEN_TITLE = "K_CMS_SCREEN_TITLE"

//MARk: AddSymptomsVC
//====================
let K_ADD_SYMPTOMS_TITLE = "K_ADD_SYMPTOMS_TITLE"
let K_WRITE_SYMPTOMS = "K_WRITE_SYMPTOMS"
let K_MOST_COMMON = "K_MOST_COMMON"
let K_STRENGTH = "K_STRENGTH"
let K_FREQUENCY = "K_FREQUENCY"


//MARK: ConnectedDevicesVC
//========================
let K_APPLICATION_TITLE = "K_APPLICATION_TITLE"
let K_DEVICES_TITLE = "K_DEVICES_TITLE"
let K_CONNECTED_TITLE = "K_CONNECTED_TITLE"
let K_AVAILIABLE_TITLE = "K_AVAILIABLE_TITLE"

//MARK: Response Keys
//====================
let error_code = "error_code"
let error_string = "error_string"
let response = "response"

//MARK:- ICLOUD IDENTIFIER
//=========================
let K_ICLOUD_INDENTFIER = "K_ICLOUD_INDENTFIER"
let K_ICLOUD_PERMISSION_TEXT = "K_ICLOUD_PERMISSION_TEXT"

//MARK:- Connected Device
//========================
let K_IHEALTH = "K_IHEALTH"
let K_FITBIT = "K_FITBIT"

//MARK:- Timeline

let K_TIMELINE = "K_TIMELINE"
